// ─────────────────────────────────────────────────────────────
// prescription/rules/recognition.ts — Recognition 차원 (max=35)
// 12 actions × 5 levels. severity = Claude-Ads 차용.
// ─────────────────────────────────────────────────────────────

import type { ActionRule, PrescriptionLevel } from '../types'

export const RECOGNITION_RULES: Record<PrescriptionLevel, ActionRule[]> = {
  invisible: [
    {
      id: 'rx-rec-inv-01',
      dimension: 'recognition',
      title: 'Launch on Product Hunt',
      description: 'For AI training data to include your product, you need presence on major platforms. A Product Hunt launch is a core source AI crawlers ingest.',
      difficulty: 2,
      estimatedImpact: 8,
      timeToComplete: 'Half day',
      externalUrl: 'https://www.producthunt.com/posts/new',
      priority: 10,
      severity: 'high',
    },
    {
      id: 'rx-rec-inv-02',
      dimension: 'recognition',
      title: 'Add an llms.txt file at your domain root',
      description: 'llms.txt is a standard that helps AI accurately understand your product. Structure your product name, description, and key features and publish at /llms.txt.',
      difficulty: 1,
      estimatedImpact: 5,
      timeToComplete: '30 min',
      externalUrl: 'https://llmstxt.org',
      priority: 15,
      severity: 'high',
    },
    {
      id: 'rx-rec-inv-03',
      dimension: 'recognition',
      title: 'Post your product on Hacker News Show HN',
      description: 'HN is a core source for AI training data. Posting in the "Show HN: {product} - {one-liner}" format significantly raises the odds AI will recognize you.',
      difficulty: 2,
      estimatedImpact: 7,
      timeToComplete: '2 hours',
      externalUrl: 'https://news.ycombinator.com/showhn.html',
      priority: 12,
      severity: 'high',
    },
    {
      id: 'rx-rec-inv-04',
      dimension: 'recognition',
      title: 'Create an English Wikipedia article for your product',
      description: 'Wikipedia is in nearly every AI training set. If your product meets notability, a Wikipedia article is the surest route to AI recognition.',
      difficulty: 3,
      estimatedImpact: 10,
      timeToComplete: '1+ day',
      externalUrl: 'https://en.wikipedia.org/wiki/Wikipedia:Your_first_article',
      priority: 20,
      severity: 'medium',
    },
  ],
  emerging: [
    {
      id: 'rx-rec-emg-01',
      dimension: 'recognition',
      title: 'Create content targeting AI engines that miss you',
      description: 'Check which engines have an F grade in Engine Grades. Publish product content on the platforms that AI primarily crawls (Gemini=YouTube/Reddit, Perplexity=fresh web).',
      difficulty: 2,
      estimatedImpact: 6,
      timeToComplete: 'Half day',
      priority: 10,
      severity: 'high',
    },
    {
      id: 'rx-rec-emg-02',
      dimension: 'recognition',
      title: 'Write product use-case posts on tech blogs',
      description: 'Publish "How to use {product} for {use-case}" posts on Medium, Dev.to, and your own blog. For AI to recommend a product, it needs concrete use-case text.',
      difficulty: 2,
      estimatedImpact: 5,
      timeToComplete: '3 hours',
      priority: 15,
      severity: 'medium',
    },
  ],
  growing: [
    {
      id: 'rx-rec-grw-01',
      dimension: 'recognition',
      title: 'Tighten official docs so AI recommendations describe you accurately',
      description: "You're recognized, but inaccurate info may surface. Update meta tags, product descriptions, and FAQs on your official site so the messaging is unambiguous.",
      difficulty: 2,
      estimatedImpact: 4,
      timeToComplete: 'Half day',
      priority: 10,
      severity: 'medium',
    },
    {
      id: 'rx-rec-grw-02',
      dimension: 'recognition',
      title: 'Appear on industry podcasts and interviews',
      description: 'Podcast transcripts end up in AI training data. An interview that clearly explains your differentiation is what flips AI from "knows you" to "recommends you".',
      difficulty: 3,
      estimatedImpact: 5,
      timeToComplete: '1 day',
      priority: 15,
      severity: 'medium',
    },
  ],
  strong: [
    {
      id: 'rx-rec-str-01',
      dimension: 'recognition',
      title: 'Reach "recommended" grade on both AI engines',
      description: 'If any engine sits at grade C (recognition only), ask that AI directly to recommend your product and see what context is missing. Differentiation content vs. competitors is the lever.',
      difficulty: 2,
      estimatedImpact: 4,
      timeToComplete: 'Half day',
      priority: 10,
      severity: 'medium',
    },
    {
      id: 'rx-rec-str-02',
      dimension: 'recognition',
      title: 'Strengthen content so comparison posts list you #1',
      description: 'Being mentioned first in "Best {category}" comparisons is a core signal for AI recommendations. Beyond your own blog, ask third-party reviewers to publish comparisons.',
      difficulty: 3,
      estimatedImpact: 5,
      timeToComplete: '1 day',
      priority: 15,
      severity: 'medium',
    },
  ],
  perfect: [
    {
      id: 'rx-rec-prf-01',
      dimension: 'recognition',
      title: 'Monitor AI recognition weekly',
      description: "You're already in great shape. Use pickedby.ai Daily Pulse to track weekly changes and stay ahead of rank shifts from new entrants or AI model updates.",
      difficulty: 1,
      estimatedImpact: 1,
      timeToComplete: '10 min/week',
      priority: 50,
      severity: 'low',
    },
    {
      id: 'rx-rec-prf-02',
      dimension: 'recognition',
      title: 'Expand coverage to new AI engines (Claude, Grok)',
      description: 'Beyond the two engines we currently measure, check recognition on new AIs like Claude and Grok. Being recommended across many AIs is your long-term moat.',
      difficulty: 2,
      estimatedImpact: 2,
      timeToComplete: '2 hours',
      priority: 55,
      severity: 'low',
    },
  ],
}
